export const CONFIG = {
  ROAD: {
    WIDTH: 12,
    CHUNK_SIZE: 100,
    RENDER_DISTANCE: 6,
    COLOR: 0x1c1c1e,
    RACING_LINE_COLOR: 0xffffff,
    MARKING_EMISSIVE: 0.4,
    ROUGHNESS: 0.5,
    METALNESS: 0.3
  },
  CAR: {
    MAX_SPEED: 45,
    ACCELERATION: 15,
    STEERING: 0.045,
    DRIFT_SLIP: 0.97,
    BODY_COLOR: 0x1a1a1a,
    HEADLIGHT_COLOR: 0xffe8c0
  },
  LIGHTING: {
    HEADLIGHT_INTENSITY: 25000,
    HEADLIGHT_ANGLE: 0.35,
    HEADLIGHT_DISTANCE: 120,
    HEADLIGHT_PENUMBRA: 0.5,
    AMBIENT_COLOR: 0x1a2035,
    AMBIENT_INTENSITY: 1.0,
    HEMI_SKY_COLOR: 0x1a2a4a,
    HEMI_GROUND_COLOR: 0x0a0a0f,
    HEMI_INTENSITY: 1.0,
    STREETLIGHT_COLOR: 0xff6a00,
    STREETLIGHT_INTENSITY: 10,
    STREETLIGHT_DISTANCE: 40
  },
  VISUALS: {
    BLOOM_STRENGTH: 0.4,
    BLOOM_RADIUS: 0.4,
    BLOOM_THRESHOLD: 0.85,
    FOG_COLOR: 0x050810,
    FOG_DENSITY: 0.006,
    BACKGROUND_COLOR: 0x03050d,
    TONE_EXPOSURE: 1.0,
    CAM_FOV: 65,
    CAM_BREATH_SPEED: 0.3,
    CAM_BREATH_AMP: 0.08,
    FILM_NOISE: 0.25,
    GRAIN_SOFTNESS: 0.4
  },
  BIOMES: {
    CYCLE_DISTANCE: 800,
    LOWLANDS: {
      NAME: 'Metropolis',
      ELEVATION_SCALE: 10,
      CITY_DENSITY: 0.8,
      LANE_COUNT: 4,
      FOG_DENSITY: 0.008,
      FOG_COLOR: 0x0a0c1a
    },
    FOOTHILLS: {
      NAME: 'Foothills',
      ELEVATION_SCALE: 30,
      CITY_DENSITY: 0.0,
      LANE_COUNT: 2,
      FOG_DENSITY: 0.006,
      FOG_COLOR: 0x050810
    },
    PEAKS: {
      NAME: 'The Peaks',
      ELEVATION_SCALE: 65,
      CITY_DENSITY: 0.0,
      LANE_COUNT: 2,
      TURN_SHARPNESS: 0.8,
      FOG_DENSITY: 0.01,
      FOG_COLOR: 0x1a1a25
    }
  }
};
